name: Node.js CI

on: [push]

jobs:
  add-hosts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add test hosts to /etc/hosts
        run: |
          echo "127.0.0.1 nic.localhost" | sudo tee -a /etc/hosts
          echo "127.0.0.1 tim.localhost" | sudo tee -a /etc/hosts
          echo "127.0.0.1 nicola.localhost" | sudo tee -a /etc/hosts
          echo "127.0.0.1 ldnode.localhost" | sudo tee -a /etc/hosts
  test-node:
    needs: [add-hosts]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run test with Node.js ${{ matrix.node-version }}
      run: npm run test-node
      env:
        CI: true
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run Standard.js linter
      run: npm run standard
